In [1]:
# Some imports
import numpy as np
import pandas as pd
import datetime as dt
import matplotlib.pyplot as plt
%matplotlib inline

# Effect in # files

In [2]:
file_ents_to_compl = pd.read_csv('data_log.csv', sep=',', encoding='utf-8')

In [3]:
file_ents_to_compl

       project_id  file_id  entity_id  file_based  entity_based
0              24    26535     976732           8             7
1              24    26535     976733           8             7
2              24    26535     976734           8             6
3              24    26535     976735           8             6
4              24    26535     976736           8             6
5              24    26535     976737           8             6
6              24    26535     976738           8             7
7              24    26535     976740           8             7
8              24    26536     976745           1             1
9              24    26536     976746           1             1
10             24    26536     976747           1             1
11             24    26536     976749           1             1
12             24    26537     976754           2             2
13             24    26537     976755           2             1
14             24    26537     976756           2             1
15             24    26537     976757           2             1
16             24    26537     976758           2             1
17             24    26537     976759           2             1
18             24    26537     976760           2             1
19             24    26538     976763           1             1
20             24    26538     976765           1             1
21             24    26538     976767           1             1
22             24    26539     976788           3             3
23             24    26539     976789           3             3
24             24    26539     976790           3             2
25             24    26539     976791           3             3
26             24    26539     976792           3             3
27             24    26539     976793           3             3
28             24    26539     976794           3             3
29             24    26539     976795           3             3
...           ...      ...        ...         ...           ...
29871          71    32241    1002298           6             1
29872          71    32241    1002299           6             1
29873          71    32241    1002300           6             1
29874          71    32242    1002302           1             1
29875          71    32242    1002304           1             1
29876          71    32243    1002305           1             1
29877          71    32243    1002306           1             1
29878          71    32243    1002308           1             1
29879          71    32244    1002315          25            10
29880          71    32244    1002316          25             9
29881          71    32244    1002317          25            10
29882          71    32244    1002318          25             3
29883          71    32244    1002319          25             3
29884          71    32244    1002320          25             3
29885          71    32244    1002321          25             3
29886          71    32244    1002322          25             6
29887          71    32244    1002323          25             5
29888          71    32244    1002324          25             4
29889          71    32244    1002325          25             3
29890          71    32244    1002326          25             3
29891          71    32244    1002327          25             3
29892          71    32244    1002328          25             3
29893          71    32244    1002329          25             3
29894          71    32244    1002330          25             3
29895          71    32244    1002331          25             3
29896          71    32244    1002332          25             4
29897          71    32244    1002333          25             3
29898          71    32245    1002335          13             1
29899          71    32245    1002336          13             2
29900          71    32245    1002338          13             3

[29901 rows x 5 columns]

### Effect by project

In [8]:
pd.pivot_table(file_ents_to_compl,
               index='project_id',
               values=['file_based', 'entity_based'],
               aggfunc='median').describe()
# Difference between columns is difference in compilation efforts

       entity_based  file_based
count     48.000000   48.000000
mean       1.385417   14.354167
std        0.670341   62.437880
min        1.000000    1.000000
25%        1.000000    2.000000
50%        1.000000    3.500000
75%        2.000000    7.000000
max        4.000000  435.000000

### Effect by file

In [9]:
pd.pivot_table(file_ents_to_compl,
               index='file_id',
               values=['file_based', 'entity_based'],
               aggfunc='median').describe()
# Difference between columns is difference in compilation efforts

       entity_based   file_based
count   3405.000000  3405.000000
mean       4.316300   129.473421
std       16.316537   205.044473
min        1.000000     1.000000
25%        1.000000     1.000000
50%        1.500000     4.000000
75%        3.000000   435.000000
max      302.000000   605.000000

# Regressing project compile times

In [11]:
project_files = pd.read_csv('project_size.csv', sep=',', encoding='utf-8')

In [12]:
project_files

    project_id                                             name  count
0           24                            autotracks-web-master     26
1           25                                       AIP-master     64
2           26                               annotations-master     25
3           27                             AlquilerAutos-master     11
4           28                    BankAccount_19_06_2013-master      9
5           29                                        bc-master      9
6           30                                 blacklist-master     41
7           31                    bndtools.runtime.junit-master     10
8           32                       CorrectiveEvolution-master    120
9           33                             cr_testsuites-master    157
10          34                       CS1699-Deliverable3-master     18
11          35                          cs56-games-poker-master     14
12          36               cs56-utilities-cryptography-master     17
13          37                   DesignAndTestAssignment-master     29
14          38                     ehcache-json-provider-master     11
15          39                                       exp-master     29
16          40                                        ga-master      9
17          41                           finite_automata-master     15
18          42                                    hotciv-master     80
19          43                                     irc4j-master     92
20          44                                   iWeight-master     33
21          45                                JavaBasico-master    101
22          46                              JavaTraining-master     77
23          47                                      jdbm-master    121
24          48                                 KiisuV2lk-master    107
25          49                                      lab5-master     16
26          50                          lattice-sequence-master     81
27          51                       Log121-Laboratoire3-master     27
28          52                                      Maya-master     10
29          53                             MMT_Connector-master     21
30          54      ModernWebDevelopment_Homework_7_full-master     24
31          55                                     mymom-master    730
32          56                              nashorn-jdom-master     13
33          57                                  NeoDatis-master   1067
34          58                                projet_msn-master     52
35          59                       refactoringExercise-master     43
36          60                                       si1-master     21
37          61                                  simpledb-master    101
38          62                        solr-spatial-light-master     36
39          63                                       SQM-master     11
40          64                          strawberryhunter-master     34
41          65  SurvivingLegacyCode-Annecy-September2014-master      9
42          66                         TddCalculatorJava-master      8
43          67                                       TP2-master     53
44          68                                  Training-master     56
45          69             TWU_biblioteca_tmorrisandjosh-master     14
46          70                          universa-appbank-master     40
47          71                            wt-mail-server-master     44